### ISSUE TITLE
Bug in Nightly with any theme

### ISSUE THREAD

**Issue by ghost** [dannycandle/FluidFox#1]
![Screenshot (10)](https://user-images.githubusercontent.com/104303586/193080290-185c87b7-56e2-49a9-9f08-d0728417e24a.png)

**Comment by dannycandle** [comment]
Thank you for letting me know. Are you on Windows?

**Comment by brunomiguel** [comment]
I have the same issue on Linux, with the production version of Firefox

**Comment by ghost** [comment]
> Thank you for letting me know. Are you on Windows?

Yes, this is Windows 10 LTSC.

**Comment by dannycandle** [comment]
@brunomiguel @Morgan-le-Fay Apologies for the confusion, this userChrome uses native mac OS styling that will only work on that platform. Possibility of adding additional native elements for other platforms in the future. Thank you.

**Comment by ghost** [comment]
> @brunomiguel @Morgan-le-Fay Apologies for the confusion, this userChrome uses native mac OS styling that will only work on that platform. Possibility of adding additional native elements for other platforms in the future. Thank you.

Ah! The theme looks great. Good luck on future updates.
